### ISSUE TITLE
Decoding string value of only + (unquoted) fails

### ISSUE THREAD

**Issue by TBeijen** [zclconf/go-cty-yaml#13]
## Behaviour

When decoding yaml documents having values of just `+` (unquoted), decoding fails with the following error:

```
cannot parse "+" as tag:yaml.org,2002:int
```

## Expected

The `+` values to be interpreted as string

## Additional info

Encountered this error while using Terraform `yamldecode` function, which uses `go-cty-yaml`.

See temporary repo that illustrates the error: https://github.com/TBeijen/terraform-go-cty-yaml-decode-error

Sample document triggering error:

```yaml
name: +
web_origins:
  - /foobar
```

**Comment by apparentlymart** [comment]
Thanks! This is now fixed in version 1.1.0, thanks to your work in https://github.com/zclconf/go-cty-yaml/pull/14.
