### ISSUE TITLE
`YAMLDecodeFunc` mishandling numbers that end in `.0` 

### ISSUE THREAD

**Issue by ghost** [zclconf/go-cty-yaml#5]
Copied from [#22223](https://github.com/hashicorp/terraform/issues/22223)

`yamldecode` is a terraform function which directly calls `YAMLDecodeFunc` from `go-cty-yaml`. It eats numbers that end in `.0`:

```
> yamldecode("version: '1.0'")
{
  "version" = "1"
}
> yamldecode("version: '1.00'")
{
  "version" = "1"
}

> yamldecode("version: 1.0")
{
  "version" = 1
}

Decimal-looking strings not ending in zero parse correctly:

> yamldecode("version: '1.01'")
{
  "version" = "1.01"
}
```

**Comment by apparentlymart** [comment]
I think #4 has fixed this already, but it's not in a release tag and thus Terraform doesn't yet have that fix.

**Comment by cspargo** [comment]
also seeing this, dropping leading zeros of a string that looks like a number

```
> yamldecode("version: '003'")
{
  "version" = "3"
}
```

**Comment by ghost** [comment]
Confirmed, and apologies for the outdated issue!
